config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/tasks', to: 'tasks#index'
  post '/tasks', to: 'tasks#create'
  get '/tasks/new', to: 'tasks#new'
  get '/tasks/:id', to: 'tasks#show', as: :task
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to tasks_path
  end

  def edit; end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path, status: :see_other
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.label :title, :class => 'form-label' %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-12 col-lg-6">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-lg-6">
      <%= f.label :details, :class => 'form-label' %>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-12 col-lg-6">
      <%= f.text_area :details, :class => 'form-control' %>
    </div>
  </div>
  <% if task.persisted? %>
    <div class="row mb-2">
      <div class="col-12 col-lg-6">
        <%= f.check_box :completed %>
        <%= f.label :completed, "This task is completed" %>
      </div>
    </div>
  <% end %>
  <div class="row mt-2">
    <div class="col-12 col-lg-6">
      <%= f.submit :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit your task</h1>

<%= render "form", task: @task %>
<br>
<%= link_to "Back to tasks", tasks_path %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<ol>
  <% @tasks.each do |task| %>
    <li>
        <% check_icon = task.completed ? "fa-square-check" : "fa-square" %>
        <i class="fa-regular <%= check_icon %>"></i>
        <%= link_to task.title, task_path(task) %>
        (<%= task.details %>)
        <%= link_to "✏️", edit_task_path(task) %>
        <%= link_to "🗑", task_path(task), data: {turbo_method: :delete,
          turbo_confirm: "Are you sure?"} %>
    </li>
  <% end %>
</ol>

<%= link_to "+ Add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>

<p>
  <% check_icon = @task.completed ? "fa-square-check" : "fa-square" %>
  <i class="fa-regular <%= check_icon %>"></i>
  This tasks is <%= @task.completed ? "complete!" : "not completed yet!" %>
</p>
<%= link_to "Back to tasks", tasks_path %>